version: '3'

services:
  node: &app_base
    image: node:11.14.0-alpine
    tty: true
    working_dir: /var/www
    volumes:
      # - ./dev_thincro:/var/www
      - ./dev_thincro:/var/www:cached
      # - ./docker/workspace/yarn_cache:/usr/local/share/.cache/yarn/v4
    environment:
      PORT: 9090
      HOST: 0.0.0.0
    # restart: always
    # networks:
    #   - default
    links:
      - dynamo-admin



  workspace:
    <<: *app_base
    ports:
      - "127.0.0.1:${HTTP_PORT}:9090"
    command: yarn dev
    # networks:
    #   - default
    # links:
    #   - dynamo-admin


  dynamo-admin:
    image: instructure/dynamo-local-admin
    ports:
      - "127.0.0.1:9092:8001"
    volumes:
      - ./db_data:/var/lib/dynamodb
    # networks:
    #   - default

  aws-cli:
    container_name: 'aws-cli'
    image: aws-s3/aws-cli
    build:
      context: ./
      dockerfile: ./docker/aws-cli/Dockerfile
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
    networks:
      - default
    links:
      - dynamo-admin

