version: '3'

services:
  node: &app_base
    image: node:11.14.0-alpine
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    environment:
      PORT: 9090
      HOST: 0.0.0.0

  workspace:
    <<: *app_base
    ports:
      - "127.0.0.1:${HTTP_PORT}:9090"
    command: yarn dev

